name: Deploy Admin Resources

on:
  push:
    branches:
      - main
    paths:
      - 'infra-admin/**'  # Trigger only when changes are made to the infra-admin

jobs:
  deploy-ecr-bastion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Initialize Terraform
        working-directory: ./infra-admin
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ./infra-admin
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: ./infra-admin
        run: terraform apply -auto-approve -input=false


