name: Deploy EKS Cluster

on:
  push:
    branches:
      - main
    paths:
      - 'eks-cluster/**'  # Trigger only when changes are made to the eks-cluster directory

jobs:
  build-eks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Initialize Terraform
        working-directory: ./eks-cluster
        env:
          TF_VAR_region: us-east-1
          TF_VAR_cluster: rigetti-demo
          TF_VAR_cluster_version: "1.32"  # EKS version
          TF_VAR_ami_type: "AL2_x86_64"
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ./eks-cluster
        env:
          TF_VAR_region: us-east-1
          TF_VAR_cluster: rigetti-demo
          TF_VAR_cluster_version: "1.32"
          TF_VAR_ami_type: "AL2_x86_64"
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: ./eks-cluster
        env:
          TF_VAR_region: us-east-1
          TF_VAR_cluster: rigetti-demo
          TF_VAR_cluster_version: "1.32"
          TF_VAR_ami_type: "AL2_x86_64"
        run: terraform apply -auto-approve -input=false

      
